import Head from 'next/head'

export default function Create() {
    return(
        <><Head>
        <title>Create your NanuTok!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Create your on NanuTok!</h2>

        <style jsx>{`
            h2 {
                text-align: center;
                font-size: 2rem;
                margin-top: 2rem;
            }
        `}</style>
        </>
    )
}