import Head from 'next/head'

export default function Create() {
    return(
        <><Head>
        <title>Create your NanuTok!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>Create</>
    )
}