import Head from 'next/head'
import InboxHeader from '../../components/InboxHeader'

export default function Inbox() {
    return(
        <><Head>
        <title>Inbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <InboxHeader />
        </>
    )
}