import Head from 'next/head'

import SearchHeader from '../../components/SearchHeader'
import SearchCarrousel from '../../components/SearchCarrousel'
import RecommendedHashtag from '../../components/RecommendedHashtag'

export default function Search() {
    return(
        <>
        <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <SearchHeader />
        
        <div className="search" style={{marginBottom:'8vh', paddingTop:'10vh'}}>
            <SearchCarrousel />
            <RecommendedHashtag />
            <RecommendedHashtag />
            <RecommendedHashtag />
            <RecommendedHashtag />
        </div>
        
        </>
    )
}