import Head from 'next/head'

export default function Search() {
    return(
        <>
        <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        Search</>
    )
}