import Head from 'next/head'
import ProfileResume from '../../components/ProfileResume'

export default function Profile({ user }) {
    return(
        <>
        <Head>
        <title>{`{user}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <ProfileResume />
        
        </>
    )
}