import Head from 'next/head'
import ProfileResume from '../../components/ProfileResume'

export default function Profile() {

    const user = {
        username: 'habaneropicantito',
        profilePicture: '/images/profile.jpeg',
        statistics: {
            posts: 10,
            followers: 12,
            following: 6,
            likes:3000
        },
        description: 'bang bang bang',
        email: 'nawesan12@gmail.com',
        password:'12345678',
        videos: {
            personalVideos: [{
                id:1, 
                likes:10, 
                commentsCount:10, 
                comments:[{user: 'vani', comment:'hola nawe'}], 
                views:10, 
                description:'This is a video', 
                url:''},
                {
                id:2,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
                {
                id:3,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
                {
                id:4,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
                {
                id:5,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
                {
                id:6,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
                {
                id:7,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
                {
                id:8,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
                {
                id:9,
                likes:20,
                commentsCount:15,
                comments:[{user: 'vani', comment:'hola naweuu'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:20,
                description:'Second video on NanuTok',
                url:''
                },
            ],
            likedVideos: [{
                id:1,
                user: 'vani',
                likes:27,
                commentsCount:2,
                comments:[{user: 'vani', comment:'hola holaa'}, {user: 'alejandra', comment:'que buen videoo'}],
                views:22,
                description:'Im a random video',
                url:''}
            ],
            privateVideos:[]
        }
    }

    return(
        <>
        <Head>
        <title>@{user.username}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <ProfileResume user={user}/>
        
        </>
    )
}