import Head from 'next/head'

export default function Live() {
    return(
        <><Head>
        <title>Live - {`{user}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>Live</>
    )
}